# Generated by Django 5.1.15 on 2026-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userstate_last_reminded_on_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='last_streak_nudge_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
